### ISSUE TITLE
Failed to establish a new connection when deloy pythonanywhere

### ISSUE THREAD

**Issue by lavanphat** [pusher/push-notifications-python#24]
![Capture](https://user-images.githubusercontent.com/45566810/68991648-6ec76f00-0893-11ea-9bfb-398369caa345.PNG)
hello, I used beam to push the notification from web django to android but when the web was in the local host the notification was sent but when deloy went up to pythonanywhere the HTTPSConnectionPool error (host = '746eae18-a178-4f92-9bf7-61fd8cbaff9e. pushnotifications.pusher.com ', port = 443): Max retries exceeded with url: / publish_api / v1 / instances / 746eae18-a178-4f92-9bf7-61fd8cbaff9e / publishes / interests (Caused by NewConnectionError (' <urllib3.connection.VerifiedHTTPSConnection object at 0x7f0e8c2676a0>: Failed to establish a new connection: [Errno 111] Connection refused '))
Hope you can help me solve this problem

**Comment by jonathanlloyd** [comment]
@lavanphat Hi! Thanks for the issue report.
If you upgrade to version 2.0.0, your issue should be resolved.

**Comment by lavanphat** [comment]
I succeeded when upgrading version 2.0.0
